language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "pypy"
      env: PYPY_VERSION="5.3.1" NO_COVERAGE=1
cache:
  - pip
  - directories:
    - $HOME/.pyenv_cache

before_install:
  - |
      if [[ -n "$PYPY_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pypy/releases/download/0.1.0/setup-pypy.sh
        source setup-pypy.sh
      fi
install:
  - pip install --upgrade pip # Upgrade pip to get wheel caching
  # Install txacme from fork (issue #83)
  - pip install git+https://github.com/JayH5/txacme.git@issue-83-challenge-body
  # Install libcloud for txacme (issue #80)
  - pip install apache-libcloud
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi
script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_OPT="--cov"; else COVERAGE_OPT=""; fi
  - py.test marathon_acme $COVERAGE_OPT
  - flake8 .
after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
