language: python
matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: pypy
      env: PYENV_VERSION=pypy-5.4.1 PYENV_VERSION_STRING='PyPy 5.4.1' NO_COVERAGE=1
cache:
  - pip
  - directories:
    - ~/.pyenv_cache

before_install:
  - |
      if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.2.0/setup-pyenv.sh
        source setup-pyenv.sh
      fi
install:
  - pip install --upgrade pip # Upgrade pip to get wheel caching
  # Install txacme from master
  - pip install git+https://github.com/mithrandi/txacme.git
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi
script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_OPT="--cov"; else COVERAGE_OPT=""; fi
  - py.test marathon_acme $COVERAGE_OPT
  - flake8 .
after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi
